using System;
using System.Collections.Generic;
using UnityEngine;

internal class ILNEMMEIHHJ
{
	private enum JMNHFPAPILG
	{
		kInput = 0,
		kOutput = 1
	}

	private static Dictionary<int, ComputeBuffer> DIPOHONEJBK;

	private static bool PNDDHMBIMON;

	private static int JHPLGIAHOPB;

	private static int BOBODDKMAHL;

	private static int JGMCDDCGMKF;

	private static int KGACHAEHPOM;

	private static int DNOFECGPCPI;

	private static int DFAIMCMCGKA;

	private static int OHIDADIFOOG;

	private static int HHOHCNNFPNF;

	private static int PHOMIPKJCPB;

	private static int HEGEDPEJKPN;

	private static int HFLLEDNPCHM;

	private static int CFANLKEJNNP;

	private static int HOEPIPFJMGC;

	internal static void KJJNMIKGEGF(KBOIGCLODLE CGOPKGNIBEO, KBOIGCLODLE NPEFIKEMDAI, ComputeShader DHOBMEBHCOG, int FOLLHJLKELA, MPIBHBMFMBB DNOEFOHEKNK, JFMOEPMIEOD JNIBMEKOAJK, MJENLBLNHEL GNONGKINKAC, int OGDFKJPDING, float LKHAIHGGNBI)
	{
	}

	private static int[] FLDJJDBFNON(Array BNDDAPNOBJB)
	{
		return null;
	}

	internal static void NPILKBFFNLN(KBOIGCLODLE NPEFIKEMDAI, ComputeShader DHOBMEBHCOG, int FOLLHJLKELA, float GDCHMDGDLLA)
	{
	}

	private static ComputeBuffer GLKMPDILKIH(int HEJFONJAMFF, int NKIHALBPGAI, JMNHFPAPILG ICOKMFIBMCM)
	{
		return null;
	}

	private static ComputeBuffer OCACMADJOCD(ComputeShader DHOBMEBHCOG, int FOLLHJLKELA, Array NPEFIKEMDAI, int[] HNFECNJNIAB)
	{
		return null;
	}

	internal static float CJGFKHPONEB(float GDCHMDGDLLA)
	{
		return 0f;
	}

	private static ComputeBuffer HCEEKDGDADH(ComputeShader DHOBMEBHCOG, int FOLLHJLKELA, Array CGOPKGNIBEO, Array NPEFIKEMDAI)
	{
		return null;
	}

	internal static void IAEDFFNLGKD(KBOIGCLODLE NPEFIKEMDAI, ComputeShader DHOBMEBHCOG, int FOLLHJLKELA, MPIBHBMFMBB DNOEFOHEKNK, JFMOEPMIEOD JNIBMEKOAJK, MJENLBLNHEL GNONGKINKAC, int OGDFKJPDING, float LKHAIHGGNBI)
	{
	}

	internal static float EKNECLGINJC(float GDCHMDGDLLA)
	{
		return 0f;
	}

	internal static float HDFNCOJMBFI(float GDCHMDGDLLA)
	{
		return 0f;
	}

	internal static void CLNMMKDEJAO(KBOIGCLODLE NPEFIKEMDAI, ComputeShader DHOBMEBHCOG, int FOLLHJLKELA, MPIBHBMFMBB DNOEFOHEKNK, JFMOEPMIEOD JNIBMEKOAJK, int OGDFKJPDING, float LKHAIHGGNBI)
	{
	}

	internal static void MHGKIDFDOMB(KBOIGCLODLE NPEFIKEMDAI, ComputeShader DHOBMEBHCOG, int FOLLHJLKELA, MPIBHBMFMBB DNOEFOHEKNK, JFMOEPMIEOD JNIBMEKOAJK, MJENLBLNHEL GNONGKINKAC, int OGDFKJPDING, float LKHAIHGGNBI)
	{
	}

	internal static void CMHBCAAPMOA(KBOIGCLODLE CGOPKGNIBEO, KBOIGCLODLE NPEFIKEMDAI, ComputeShader DHOBMEBHCOG, int FOLLHJLKELA, MPIBHBMFMBB DNOEFOHEKNK, JFMOEPMIEOD JNIBMEKOAJK, int OGDFKJPDING, float LKHAIHGGNBI)
	{
	}

	internal static void JBAMBKACKFO(KBOIGCLODLE NPEFIKEMDAI, ComputeShader DHOBMEBHCOG, int FOLLHJLKELA, float GDCHMDGDLLA)
	{
	}

	internal static void CDGHKCKMACB(KBOIGCLODLE NPEFIKEMDAI, ComputeShader DHOBMEBHCOG, int FOLLHJLKELA, MPIBHBMFMBB DNOEFOHEKNK, JFMOEPMIEOD JNIBMEKOAJK, MJENLBLNHEL GNONGKINKAC, int OGDFKJPDING, float LKHAIHGGNBI)
	{
	}

	private static int[] MNCKOJLADNJ(Array BNDDAPNOBJB)
	{
		return null;
	}

	private static void MEFHOADHMEE()
	{
	}

	internal static void GLPBDHOIJJF(KBOIGCLODLE CGOPKGNIBEO, KBOIGCLODLE NPEFIKEMDAI, ComputeShader DHOBMEBHCOG, int FOLLHJLKELA, MPIBHBMFMBB DNOEFOHEKNK, JFMOEPMIEOD JNIBMEKOAJK, int OGDFKJPDING, float LKHAIHGGNBI)
	{
	}

	internal static void NPILKBFFNLN(KBOIGCLODLE CGOPKGNIBEO, KBOIGCLODLE NPEFIKEMDAI, ComputeShader DHOBMEBHCOG, int FOLLHJLKELA, MPIBHBMFMBB DNOEFOHEKNK, JFMOEPMIEOD JNIBMEKOAJK, int OGDFKJPDING, float LKHAIHGGNBI)
	{
	}

	internal static void HGMNHMLNJCF(KBOIGCLODLE NPEFIKEMDAI, ComputeShader DHOBMEBHCOG, int FOLLHJLKELA, MPIBHBMFMBB DNOEFOHEKNK, JFMOEPMIEOD JNIBMEKOAJK, MJENLBLNHEL GNONGKINKAC, int OGDFKJPDING, float LKHAIHGGNBI)
	{
	}

	private static ComputeBuffer NKOCGCFDKKP(ComputeShader DHOBMEBHCOG, int FOLLHJLKELA, Array NPEFIKEMDAI, int[] HNFECNJNIAB)
	{
		return null;
	}

	internal static void LHOEOOIKLNE(KBOIGCLODLE CGOPKGNIBEO, KBOIGCLODLE NPEFIKEMDAI, ComputeShader DHOBMEBHCOG, int FOLLHJLKELA, MPIBHBMFMBB DNOEFOHEKNK, JFMOEPMIEOD JNIBMEKOAJK, int OGDFKJPDING, float LKHAIHGGNBI)
	{
	}

	internal static float NKBHKKFHKEA(float GDCHMDGDLLA)
	{
		return 0f;
	}

	internal static float AELNHNLOPHG(float GDCHMDGDLLA)
	{
		return 0f;
	}

	private static void IEDLKOJPIIF()
	{
	}

	private static ComputeBuffer HHBPINMIKHG(int HEJFONJAMFF, int NKIHALBPGAI, JMNHFPAPILG ICOKMFIBMCM)
	{
		return null;
	}

	internal static void NPILKBFFNLN(KBOIGCLODLE NPEFIKEMDAI, ComputeShader DHOBMEBHCOG, int FOLLHJLKELA, MPIBHBMFMBB DNOEFOHEKNK, JFMOEPMIEOD JNIBMEKOAJK, int OGDFKJPDING, float LKHAIHGGNBI)
	{
	}

	private static ComputeBuffer BOPALCNAEIJ(ComputeShader DHOBMEBHCOG, int FOLLHJLKELA, Array CGOPKGNIBEO, Array NPEFIKEMDAI)
	{
		return null;
	}

	private static int[] NJNINNIPDIN(Array BNDDAPNOBJB)
	{
		return null;
	}

	private static int[] DEMPMJMPIID(Array BNDDAPNOBJB)
	{
		return null;
	}

	private static ComputeBuffer OKFJIMJFLLA(ComputeShader DHOBMEBHCOG, int FOLLHJLKELA, Array CGOPKGNIBEO, Array NPEFIKEMDAI)
	{
		return null;
	}

	internal static void CCHBJAPDANM(KBOIGCLODLE NPEFIKEMDAI, ComputeShader DHOBMEBHCOG, int FOLLHJLKELA, MPIBHBMFMBB DNOEFOHEKNK, JFMOEPMIEOD JNIBMEKOAJK, int OGDFKJPDING, float LKHAIHGGNBI)
	{
	}

	private static ComputeBuffer FBINAEMJJKI(int HEJFONJAMFF, int NKIHALBPGAI, JMNHFPAPILG ICOKMFIBMCM)
	{
		return null;
	}

	internal static void HFJNFMAFMDN(KBOIGCLODLE NPEFIKEMDAI, ComputeShader DHOBMEBHCOG, int FOLLHJLKELA, float GDCHMDGDLLA)
	{
	}

	private static ComputeBuffer OMMLHPILNDG(int HEJFONJAMFF, int NKIHALBPGAI, JMNHFPAPILG ICOKMFIBMCM)
	{
		return null;
	}

	private static void HKBJJFFIKPP()
	{
	}

	private static int[] POANJIFLFFH(Array BNDDAPNOBJB)
	{
		return null;
	}

	internal static float CHHLKBGDCIP(float GDCHMDGDLLA)
	{
		return 0f;
	}

	private static ComputeBuffer KAFLJANHIKF(ComputeShader DHOBMEBHCOG, int FOLLHJLKELA, Array NPEFIKEMDAI, int[] HNFECNJNIAB)
	{
		return null;
	}

	private static void IDINJDBPMIJ()
	{
	}

	internal static float IBDPCOMOKHA(float GDCHMDGDLLA)
	{
		return 0f;
	}

	internal static void KGLMEJICBBG(KBOIGCLODLE CGOPKGNIBEO, KBOIGCLODLE NPEFIKEMDAI, ComputeShader DHOBMEBHCOG, int FOLLHJLKELA, MPIBHBMFMBB DNOEFOHEKNK, JFMOEPMIEOD JNIBMEKOAJK, MJENLBLNHEL GNONGKINKAC, int OGDFKJPDING, float LKHAIHGGNBI)
	{
	}

	private static ComputeBuffer PMPLDDLANID(int HEJFONJAMFF, int NKIHALBPGAI, JMNHFPAPILG ICOKMFIBMCM)
	{
		return null;
	}

	private static void FGAFPCGNNFN()
	{
	}

	internal static void NPILKBFFNLN(KBOIGCLODLE NPEFIKEMDAI, ComputeShader DHOBMEBHCOG, int FOLLHJLKELA, MPIBHBMFMBB DNOEFOHEKNK, JFMOEPMIEOD JNIBMEKOAJK, MJENLBLNHEL GNONGKINKAC, int OGDFKJPDING, float LKHAIHGGNBI)
	{
	}

	private static ComputeBuffer MJLAHICGGCG(ComputeShader DHOBMEBHCOG, int FOLLHJLKELA, Array CGOPKGNIBEO, Array NPEFIKEMDAI)
	{
		return null;
	}

	internal static void GBABLEAOMHN(KBOIGCLODLE NPEFIKEMDAI, ComputeShader DHOBMEBHCOG, int FOLLHJLKELA, float GDCHMDGDLLA)
	{
	}

	private static int[] EFCBLPIBEOF(Array BNDDAPNOBJB)
	{
		return null;
	}

	private static ComputeBuffer DBBMMFLMLEP(ComputeShader DHOBMEBHCOG, int FOLLHJLKELA, Array NPEFIKEMDAI, int[] HNFECNJNIAB)
	{
		return null;
	}

	private static ComputeBuffer MLCFNECGGFC(int HEJFONJAMFF, int NKIHALBPGAI, JMNHFPAPILG ICOKMFIBMCM)
	{
		return null;
	}

	private static ComputeBuffer GODMBBPLCPO(int HEJFONJAMFF, int NKIHALBPGAI, JMNHFPAPILG ICOKMFIBMCM)
	{
		return null;
	}

	internal static void CPLACJKMJCP(KBOIGCLODLE NPEFIKEMDAI, ComputeShader DHOBMEBHCOG, int FOLLHJLKELA, MPIBHBMFMBB DNOEFOHEKNK, JFMOEPMIEOD JNIBMEKOAJK, MJENLBLNHEL GNONGKINKAC, int OGDFKJPDING, float LKHAIHGGNBI)
	{
	}

	internal static void KIFNMFOCBCH(KBOIGCLODLE CGOPKGNIBEO, KBOIGCLODLE NPEFIKEMDAI, ComputeShader DHOBMEBHCOG, int FOLLHJLKELA, MPIBHBMFMBB DNOEFOHEKNK, JFMOEPMIEOD JNIBMEKOAJK, int OGDFKJPDING, float LKHAIHGGNBI)
	{
	}

	private static int[] DMDEBPDHLFM(Array BNDDAPNOBJB)
	{
		return null;
	}

	internal static void NFHINFIMEMI(KBOIGCLODLE CGOPKGNIBEO, KBOIGCLODLE NPEFIKEMDAI, ComputeShader DHOBMEBHCOG, int FOLLHJLKELA, MPIBHBMFMBB DNOEFOHEKNK, JFMOEPMIEOD JNIBMEKOAJK, int OGDFKJPDING, float LKHAIHGGNBI)
	{
	}

	internal static void BNFBOGBMHBH(KBOIGCLODLE CGOPKGNIBEO, KBOIGCLODLE NPEFIKEMDAI, ComputeShader DHOBMEBHCOG, int FOLLHJLKELA, MPIBHBMFMBB DNOEFOHEKNK, JFMOEPMIEOD JNIBMEKOAJK, MJENLBLNHEL GNONGKINKAC, int OGDFKJPDING, float LKHAIHGGNBI)
	{
	}

	internal static void NPILKBFFNLN(KBOIGCLODLE CGOPKGNIBEO, KBOIGCLODLE NPEFIKEMDAI, ComputeShader DHOBMEBHCOG, int FOLLHJLKELA, MPIBHBMFMBB DNOEFOHEKNK, JFMOEPMIEOD JNIBMEKOAJK, MJENLBLNHEL GNONGKINKAC, int OGDFKJPDING, float LKHAIHGGNBI)
	{
	}

	private static ComputeBuffer GDENKDBNKJD(int HEJFONJAMFF, int NKIHALBPGAI, JMNHFPAPILG ICOKMFIBMCM)
	{
		return null;
	}

	internal static void FOLLPCNNPGI(KBOIGCLODLE NPEFIKEMDAI, ComputeShader DHOBMEBHCOG, int FOLLHJLKELA, MPIBHBMFMBB DNOEFOHEKNK, JFMOEPMIEOD JNIBMEKOAJK, int OGDFKJPDING, float LKHAIHGGNBI)
	{
	}

	internal static void NLOBGBDEGOK(KBOIGCLODLE NPEFIKEMDAI, ComputeShader DHOBMEBHCOG, int FOLLHJLKELA, MPIBHBMFMBB DNOEFOHEKNK, JFMOEPMIEOD JNIBMEKOAJK, int OGDFKJPDING, float LKHAIHGGNBI)
	{
	}

	private static int[] NHJNPKDFFEO(Array BNDDAPNOBJB)
	{
		return null;
	}

	internal static void PKBLLHNIJBM(KBOIGCLODLE NPEFIKEMDAI, ComputeShader DHOBMEBHCOG, int FOLLHJLKELA, MPIBHBMFMBB DNOEFOHEKNK, JFMOEPMIEOD JNIBMEKOAJK, MJENLBLNHEL GNONGKINKAC, int OGDFKJPDING, float LKHAIHGGNBI)
	{
	}

	internal static void KONCLCIFAEK(KBOIGCLODLE NPEFIKEMDAI, ComputeShader DHOBMEBHCOG, int FOLLHJLKELA, MPIBHBMFMBB DNOEFOHEKNK, JFMOEPMIEOD JNIBMEKOAJK, int OGDFKJPDING, float LKHAIHGGNBI)
	{
	}

	internal static void OAGEHLKPCCD(KBOIGCLODLE NPEFIKEMDAI, ComputeShader DHOBMEBHCOG, int FOLLHJLKELA, float GDCHMDGDLLA)
	{
	}

	internal static void FHKAEPAJFAJ(KBOIGCLODLE NPEFIKEMDAI, ComputeShader DHOBMEBHCOG, int FOLLHJLKELA, MPIBHBMFMBB DNOEFOHEKNK, JFMOEPMIEOD JNIBMEKOAJK, int OGDFKJPDING, float LKHAIHGGNBI)
	{
	}

	internal static void HOHKELDLPPL(KBOIGCLODLE NPEFIKEMDAI, ComputeShader DHOBMEBHCOG, int FOLLHJLKELA, MPIBHBMFMBB DNOEFOHEKNK, JFMOEPMIEOD JNIBMEKOAJK, int OGDFKJPDING, float LKHAIHGGNBI)
	{
	}

	private static int[] LEHNNLNOCOP(Array BNDDAPNOBJB)
	{
		return null;
	}

	internal static void BMNICBPHIKG(KBOIGCLODLE CGOPKGNIBEO, KBOIGCLODLE NPEFIKEMDAI, ComputeShader DHOBMEBHCOG, int FOLLHJLKELA, MPIBHBMFMBB DNOEFOHEKNK, JFMOEPMIEOD JNIBMEKOAJK, MJENLBLNHEL GNONGKINKAC, int OGDFKJPDING, float LKHAIHGGNBI)
	{
	}

	private static void MOIDJJJJMCE()
	{
	}

	private static ComputeBuffer KINGEDAGHFC(ComputeShader DHOBMEBHCOG, int FOLLHJLKELA, Array CGOPKGNIBEO, Array NPEFIKEMDAI)
	{
		return null;
	}
}
