using System.Collections.Generic;
using UnityEngine;

public class MMOJIIONBFL
{
	public enum MBPBECHPNKP
	{
		Wireframe = 0,
		SolidColor = 1,
		FlatShaded = 2,
		SmoothShaded = 3
	}

	private static float PMIJIIFOGKF;

	private const int IMHFKKEGECK = 1;

	private const int ABKCJKCEKKI = 2;

	private const int DGKMNHAGIHC = 4;

	private static Dictionary<int, Material> GNBEIOPGNEB;

	private static MaterialPropertyBlock CPKKLIMJAKM;

	public static void JBAFMHEFJMM(Vector3 DMOJMBGJPLI, float OLBJLMOIBGP, Vector2 BMEDADIMMHB, Color OLJIIPPOIHN, bool AOGHBLBMJLB = true, MBPBECHPNKP FBDLLHEJGBG = MBPBECHPNKP.Wireframe)
	{
	}

	public static void POEOANLBDLH(Vector3 PFCFCJFDLEP, Quaternion FEJGFDOCPFG, float BBBOEPIDMHK = 0.5f)
	{
	}

	public static void EGJEPNBPGMM(Vector3[] EAPFNNIPKPN, Color OLJIIPPOIHN, bool AOGHBLBMJLB = true)
	{
	}

	public static void FGODFFPHMDK(Vector3 DMOJMBGJPLI, float OLBJLMOIBGP, Vector2 BMEDADIMMHB, Color OLJIIPPOIHN, bool AOGHBLBMJLB = true, MBPBECHPNKP FBDLLHEJGBG = MBPBECHPNKP.Wireframe)
	{
	}

	public static void JCBCHCHHBIC(Vector3 PFCFCJFDLEP, Quaternion FEJGFDOCPFG, Color ALLFDBNIHCL, Color NDIHBODFJOP, Color EJJELKNCAEB, float BBBOEPIDMHK = 0.5f)
	{
	}

	public static void OJJIEPBEJNB(Vector3 HLOMBIIHCCM, Vector3 LBCGICILAFA, Color OLJIIPPOIHN, bool AOGHBLBMJLB = true)
	{
	}

	public static void BKEEODIPCLJ(Vector3[] EAPFNNIPKPN, Color OLJIIPPOIHN, bool AOGHBLBMJLB = true)
	{
	}

	public static void DLFMKNCEBBO(Vector3 PFCFCJFDLEP, Vector3 BMNAOHFPFGA, Vector3 EFDCHHHLLPP, Vector3 GMNBLKLFLOK, Color ALLFDBNIHCL, Color NDIHBODFJOP, Color EJJELKNCAEB, float BBBOEPIDMHK = 0.5f)
	{
	}

	public static void MCKLIDNCBPL(Vector3 DMOJMBGJPLI, float OEDHLBGDIMC, int FNNJJAPJBPJ, int JKEKHIABIDH, Color OLJIIPPOIHN, bool AOGHBLBMJLB = true, MBPBECHPNKP FBDLLHEJGBG = MBPBECHPNKP.Wireframe)
	{
	}

	public static void BJLKOBFAJHI(Vector3 DMOJMBGJPLI, Vector3 JMEGOEGDMGL, float OEDHLBGDIMC, int KIFAMJPBEGI, Color OLJIIPPOIHN, bool AOGHBLBMJLB = true, MBPBECHPNKP FBDLLHEJGBG = MBPBECHPNKP.Wireframe)
	{
	}

	public static void LOAICKDFJKB(Vector3 HAPJNGLPDCN, Quaternion FEJGFDOCPFG, float AOEIBOIKGAL, float OEDHLBGDIMC, int KIFAMJPBEGI, Color OLJIIPPOIHN, bool AOGHBLBMJLB = true, MBPBECHPNKP FBDLLHEJGBG = MBPBECHPNKP.Wireframe)
	{
	}

	public static void OKIDCNGJIIN(Vector3 PFCFCJFDLEP, Vector3 BMNAOHFPFGA, Vector3 EFDCHHHLLPP, Vector3 GMNBLKLFLOK, float BBBOEPIDMHK = 0.5f)
	{
	}

	public static void EMCDNIHOHPG(Vector3 PFCFCJFDLEP, Quaternion FEJGFDOCPFG, Color ALLFDBNIHCL, Color NDIHBODFJOP, Color EJJELKNCAEB, float BBBOEPIDMHK = 0.5f)
	{
	}

	public static void OKIDCNGJIIN(Vector3 PFCFCJFDLEP, Vector3 BMNAOHFPFGA, Vector3 EFDCHHHLLPP, Vector3 GMNBLKLFLOK, Color ALLFDBNIHCL, Color NDIHBODFJOP, Color EJJELKNCAEB, float BBBOEPIDMHK = 0.5f)
	{
	}

	public static void BJLKOBFAJHI(Vector3 DMOJMBGJPLI, Quaternion FEJGFDOCPFG, float OEDHLBGDIMC, int KIFAMJPBEGI, Color OLJIIPPOIHN, bool AOGHBLBMJLB = true, MBPBECHPNKP FBDLLHEJGBG = MBPBECHPNKP.Wireframe)
	{
	}

	public static void PIGIOFAFILG(Vector3 PBIACJCPGDI, Vector3 GAOFGBAJNFH, float PJFCALALDKO, float HGOMNHHPKIA, int KIFAMJPBEGI, float BDKPMBAILAI, Color OLJIIPPOIHN, bool AOGHBLBMJLB = true, MBPBECHPNKP FBDLLHEJGBG = MBPBECHPNKP.Wireframe)
	{
	}

	public static void IDOKCNBNGCI(Vector3 PFCFCJFDLEP, Quaternion FEJGFDOCPFG, Color ALLFDBNIHCL, Color NDIHBODFJOP, Color EJJELKNCAEB, float BBBOEPIDMHK = 0.5f)
	{
	}

	public static void LOAICKDFJKB(Vector3 HAPJNGLPDCN, Vector3 PONGBDLAAGD, float OEDHLBGDIMC, int KIFAMJPBEGI, Color OLJIIPPOIHN, bool AOGHBLBMJLB = true, MBPBECHPNKP FBDLLHEJGBG = MBPBECHPNKP.Wireframe)
	{
	}

	public static void JIBIJEGIMAF(Vector3 DMOJMBGJPLI, Quaternion FEJGFDOCPFG, Vector2 BMEDADIMMHB, Color OLJIIPPOIHN, bool AOGHBLBMJLB = true, MBPBECHPNKP FBDLLHEJGBG = MBPBECHPNKP.Wireframe)
	{
	}

	public static void HCAHHJBPKPE(Vector3 DMOJMBGJPLI, Quaternion FEJGFDOCPFG, float AOEIBOIKGAL, float OEDHLBGDIMC, int GODHKIFADIL, int OPBGGLCJJHF, Color OLJIIPPOIHN, bool AOGHBLBMJLB = true, MBPBECHPNKP FBDLLHEJGBG = MBPBECHPNKP.Wireframe)
	{
	}

	public static void DCNGJLNDLKD(Vector3 PBIACJCPGDI, Vector3 GAOFGBAJNFH, float BBBOEPIDMHK, Color OLJIIPPOIHN, bool AOGHBLBMJLB = true, MBPBECHPNKP FBDLLHEJGBG = MBPBECHPNKP.Wireframe)
	{
	}

	private static Material PJMMNLDDLLK(MBPBECHPNKP FBDLLHEJGBG, bool AOGHBLBMJLB, bool DMCFHJDGEGM)
	{
		return null;
	}

	public static void NONHDIHAHNF(Vector3 HLOMBIIHCCM, Vector3 LBCGICILAFA, Color OLJIIPPOIHN, bool AOGHBLBMJLB = true)
	{
	}

	public static void MCKLIDNCBPL(Vector3 DMOJMBGJPLI, Quaternion FEJGFDOCPFG, float OEDHLBGDIMC, int FNNJJAPJBPJ, int JKEKHIABIDH, Color OLJIIPPOIHN, bool AOGHBLBMJLB = true, MBPBECHPNKP FBDLLHEJGBG = MBPBECHPNKP.Wireframe)
	{
	}

	public static void KAHEIGINIBL(Vector3 DMOJMBGJPLI, Quaternion FEJGFDOCPFG, Vector3 BMEDADIMMHB, Color OLJIIPPOIHN, bool AOGHBLBMJLB = true, MBPBECHPNKP FBDLLHEJGBG = MBPBECHPNKP.Wireframe)
	{
	}

	public static void PDFBEEEHHFN(Vector3 DMOJMBGJPLI, Vector3 PBIACJCPGDI, Vector3 JMEGOEGDMGL, float GHJDPOPELNL, float OEDHLBGDIMC, int KIFAMJPBEGI, Color OLJIIPPOIHN, bool AOGHBLBMJLB = true)
	{
	}

	public static void HCAHHJBPKPE(Vector3 LNFDKJLOEGD, Vector3 FHDCNJPNCAH, float OEDHLBGDIMC, int GODHKIFADIL, int OPBGGLCJJHF, Color OLJIIPPOIHN, bool AOGHBLBMJLB = true, MBPBECHPNKP FBDLLHEJGBG = MBPBECHPNKP.Wireframe)
	{
	}

	public static void AKABOOOFMMA(Vector3 DMOJMBGJPLI, float OEDHLBGDIMC, int KIFAMJPBEGI, Color OLJIIPPOIHN, bool AOGHBLBMJLB = true, MBPBECHPNKP FBDLLHEJGBG = MBPBECHPNKP.Wireframe)
	{
	}

	public static void GCNGPFIGJCN(Vector3 DMOJMBGJPLI, float OLBJLMOIBGP, float AOEIBOIKGAL, float OEDHLBGDIMC, int LFGMHJMJNJG, Color OLJIIPPOIHN, bool AOGHBLBMJLB = true, MBPBECHPNKP FBDLLHEJGBG = MBPBECHPNKP.Wireframe)
	{
	}

	public static void EOIPLKMDDBG(Vector3 PFCFCJFDLEP, Quaternion FEJGFDOCPFG, Color ALLFDBNIHCL, Color NDIHBODFJOP, Color EJJELKNCAEB, float BBBOEPIDMHK = 0.5f)
	{
	}

	public static void DIKKLFGBNOP(Vector3 HAPJNGLPDCN, Quaternion FEJGFDOCPFG, float AOEIBOIKGAL, float OEDHLBGDIMC, int KIFAMJPBEGI, Color OLJIIPPOIHN, bool AOGHBLBMJLB = true, MBPBECHPNKP FBDLLHEJGBG = MBPBECHPNKP.Wireframe)
	{
	}

	public static void OKIDCNGJIIN(Vector3 PFCFCJFDLEP, Quaternion FEJGFDOCPFG, Color ALLFDBNIHCL, Color NDIHBODFJOP, Color EJJELKNCAEB, float BBBOEPIDMHK = 0.5f)
	{
	}

	public static void FNAJFGHDFJK(Vector3 DMOJMBGJPLI, Quaternion FEJGFDOCPFG, float AOEIBOIKGAL, float OEDHLBGDIMC, int KIFAMJPBEGI, Color OLJIIPPOIHN, bool AOGHBLBMJLB = true, MBPBECHPNKP FBDLLHEJGBG = MBPBECHPNKP.Wireframe)
	{
	}

	public static void EHHJMEAKHEM(Vector3 DMOJMBGJPLI, Quaternion FEJGFDOCPFG, float OEDHLBGDIMC, int FNNJJAPJBPJ, int JKEKHIABIDH, Color OLJIIPPOIHN, bool AOGHBLBMJLB = true, MBPBECHPNKP FBDLLHEJGBG = MBPBECHPNKP.Wireframe)
	{
	}

	public static void FOJPNKAFGLC(Vector3[] EAPFNNIPKPN, Color OLJIIPPOIHN, bool AOGHBLBMJLB = true)
	{
	}

	public static void FNAJFGHDFJK(Vector3 LNFDKJLOEGD, Vector3 FHDCNJPNCAH, float OEDHLBGDIMC, int KIFAMJPBEGI, Color OLJIIPPOIHN, bool AOGHBLBMJLB = true, MBPBECHPNKP FBDLLHEJGBG = MBPBECHPNKP.Wireframe)
	{
	}

	public static void OKIDCNGJIIN(Vector3 PFCFCJFDLEP, Quaternion FEJGFDOCPFG, float BBBOEPIDMHK = 0.5f)
	{
	}

	public static void KMIMIGMEJMD(Vector3 PBIACJCPGDI, Vector3 GAOFGBAJNFH, float PJFCALALDKO, float HGOMNHHPKIA, int KIFAMJPBEGI, float BDKPMBAILAI, Color OLJIIPPOIHN, bool AOGHBLBMJLB = true, MBPBECHPNKP FBDLLHEJGBG = MBPBECHPNKP.Wireframe)
	{
	}

	public static void DLCNOHCJBPI(Vector3 PFCFCJFDLEP, Vector3 BMNAOHFPFGA, Vector3 EFDCHHHLLPP, Vector3 GMNBLKLFLOK, float BBBOEPIDMHK = 0.5f)
	{
	}

	public static void GNDDFBGLJEB(Vector3 DMOJMBGJPLI, Quaternion FEJGFDOCPFG, float AOEIBOIKGAL, float OEDHLBGDIMC, int KIFAMJPBEGI, Color OLJIIPPOIHN, bool AOGHBLBMJLB = true, MBPBECHPNKP FBDLLHEJGBG = MBPBECHPNKP.Wireframe)
	{
	}

	public static void FKOMELLECCG(Vector3 DMOJMBGJPLI, Quaternion FEJGFDOCPFG, Vector2 BMEDADIMMHB, Color OLJIIPPOIHN, bool AOGHBLBMJLB = true, MBPBECHPNKP FBDLLHEJGBG = MBPBECHPNKP.Wireframe)
	{
	}

	public static void KICBILLHBME(Vector3 DMOJMBGJPLI, Quaternion FEJGFDOCPFG, Vector2 BMEDADIMMHB, Color OLJIIPPOIHN, bool AOGHBLBMJLB = true, MBPBECHPNKP FBDLLHEJGBG = MBPBECHPNKP.Wireframe)
	{
	}

	public static void OIOJDJFDIHO(Vector3 DMOJMBGJPLI, float OLBJLMOIBGP, Vector2 BMEDADIMMHB, Color OLJIIPPOIHN, bool AOGHBLBMJLB = true, MBPBECHPNKP FBDLLHEJGBG = MBPBECHPNKP.Wireframe)
	{
	}

	public static void CPDGJEJLHDE(Vector3 DMOJMBGJPLI, float OLBJLMOIBGP, float AOEIBOIKGAL, float OEDHLBGDIMC, int LFGMHJMJNJG, Color OLJIIPPOIHN, bool AOGHBLBMJLB = true, MBPBECHPNKP FBDLLHEJGBG = MBPBECHPNKP.Wireframe)
	{
	}

	public static void AKONBJEIBIL(Vector3 DMOJMBGJPLI, Vector3 PBIACJCPGDI, Vector3 JMEGOEGDMGL, float GHJDPOPELNL, float OEDHLBGDIMC, int KIFAMJPBEGI, Color OLJIIPPOIHN, bool AOGHBLBMJLB = true)
	{
	}

	public static void KMIMIGMEJMD(Vector3 PBIACJCPGDI, Vector3 GAOFGBAJNFH, float BBBOEPIDMHK, Color OLJIIPPOIHN, bool AOGHBLBMJLB = true, MBPBECHPNKP FBDLLHEJGBG = MBPBECHPNKP.Wireframe)
	{
	}

	public static void ADMNIGFHNGH(Vector3 DMOJMBGJPLI, Vector3 PBIACJCPGDI, Vector3 JMEGOEGDMGL, float GHJDPOPELNL, float OEDHLBGDIMC, int KIFAMJPBEGI, Color OLJIIPPOIHN, bool AOGHBLBMJLB = true)
	{
	}

	public static void INHCLMIDLAH(Vector3 PFCFCJFDLEP, Quaternion FEJGFDOCPFG, float BBBOEPIDMHK = 0.5f)
	{
	}

	public static void CECCAGFALFA(Vector3 DMOJMBGJPLI, float OEDHLBGDIMC, int KIFAMJPBEGI, Color OLJIIPPOIHN, bool AOGHBLBMJLB = true, MBPBECHPNKP FBDLLHEJGBG = MBPBECHPNKP.Wireframe)
	{
	}

	public static void MGEOCDAGIKE(Vector3 DMOJMBGJPLI, Quaternion FEJGFDOCPFG, float OEDHLBGDIMC, int KIFAMJPBEGI, Color OLJIIPPOIHN, bool AOGHBLBMJLB = true, MBPBECHPNKP FBDLLHEJGBG = MBPBECHPNKP.Wireframe)
	{
	}

	private static MaterialPropertyBlock NIBEMKJMCEF()
	{
		return null;
	}

	public static void LOEJGGFBAGI(Vector3 DMOJMBGJPLI, Quaternion FEJGFDOCPFG, float AOEIBOIKGAL, float OEDHLBGDIMC, int GODHKIFADIL, int OPBGGLCJJHF, Color OLJIIPPOIHN, bool AOGHBLBMJLB = true, MBPBECHPNKP FBDLLHEJGBG = MBPBECHPNKP.Wireframe)
	{
	}

	public static void IIGIOLCBKOB(Vector3 LNFDKJLOEGD, Vector3 FHDCNJPNCAH, float OEDHLBGDIMC, int GODHKIFADIL, int OPBGGLCJJHF, Color OLJIIPPOIHN, bool AOGHBLBMJLB = true, MBPBECHPNKP FBDLLHEJGBG = MBPBECHPNKP.Wireframe)
	{
	}

	public static void NFMIGNHPJNL(Vector3 DMOJMBGJPLI, float OLBJLMOIBGP, float AOEIBOIKGAL, float OEDHLBGDIMC, int LFGMHJMJNJG, Color OLJIIPPOIHN, bool AOGHBLBMJLB = true, MBPBECHPNKP FBDLLHEJGBG = MBPBECHPNKP.Wireframe)
	{
	}

	public static void MGEOCDAGIKE(Vector3 DMOJMBGJPLI, float OEDHLBGDIMC, int KIFAMJPBEGI, Color OLJIIPPOIHN, bool AOGHBLBMJLB = true, MBPBECHPNKP FBDLLHEJGBG = MBPBECHPNKP.Wireframe)
	{
	}
}
