using UnityEngine;

public interface MNBFFOCOFHJ
{
	bool CDJBEIDLNPC(string KKFJCHKHPDD, MMDBDCPJADG AKFAFAFOEHI);

	bool CDJBEIDLNPC(byte[] JIHLFCODLMP, MMDBDCPJADG AKFAFAFOEHI);

	bool LHJMHDKIBLC(string LNMDPMBMJBI, string EKCMFDKHEOF, bool MJEFMEKEAEO);

	Texture2D EKBGFEDIBGF(string MKMGOIACMHB, float CCKIOGLFDBF);

	bool LHJMHDKIBLC(byte[] JIHLFCODLMP, string EKCMFDKHEOF);
}
