using System.ComponentModel;

namespace Microsoft.CSharp.RuntimeBinder
{
	/// <summary>Represents information about C# dynamic operations that are specific to particular arguments at a call site. Instances of this class are generated by the C# compiler.</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public sealed class CSharpArgumentInfo
	{
		internal static readonly CSharpArgumentInfo None;

		private CSharpArgumentInfoFlags Flags { get; }

		internal string Name { get; }

		internal bool UseCompileTimeType => false;

		internal bool LiteralConstant => false;

		internal bool NamedArgument => false;

		internal bool IsByRefOrOut => false;

		internal bool IsOut => false;

		internal bool IsStaticType => false;

		private CSharpArgumentInfo(CSharpArgumentInfoFlags flags, string name)
		{
		}

		/// <summary>Initializes a new instance of the <see cref="T:Microsoft.CSharp.RuntimeBinder.CSharpArgumentInfo" /> class.</summary>
		/// <returns>A new instance of the <see cref="T:Microsoft.CSharp.RuntimeBinder.CSharpArgumentInfo" /> class.</returns>
		/// <param name="flags">The flags for the argument.</param>
		/// <param name="name">The name of the argument, if named; otherwise null.</param>
		public static CSharpArgumentInfo Create(CSharpArgumentInfoFlags flags, string name)
		{
			return null;
		}
	}
}
