namespace MidiPlayerTK
{
	public enum fluid_voice_envelope_index
	{
		FLUID_VOICE_ENVDELAY = 0,
		FLUID_VOICE_ENVATTACK = 1,
		FLUID_VOICE_ENVHOLD = 2,
		FLUID_VOICE_ENVDECAY = 3,
		FLUID_VOICE_ENVSUSTAIN = 4,
		FLUID_VOICE_ENVRELEASE = 5,
		FLUID_VOICE_ENVFINISHED = 6,
		FLUID_VOICE_ENVLAST = 7
	}
}
