<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>MIDIUnified</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <OutputType>Exe</OutputType>
    <TargetFramework>net40</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>9.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\..\Assemblies\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>..\..\Assemblies\UnityEngine.UI.dll</HintPath>
    </Reference>
    <Reference Include="ForieroEngine">
      <HintPath>..\..\Assemblies\ForieroEngine.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AudioModule">
      <HintPath>..\..\Assemblies\UnityEngine.AudioModule.dll</HintPath>
    </Reference>
    <Reference Include="midi_win_store">
      <HintPath>..\..\Assemblies\midi_win_store.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.PhysicsModule">
      <HintPath>..\..\Assemblies\UnityEngine.PhysicsModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.InputLegacyModule">
      <HintPath>..\..\Assemblies\UnityEngine.InputLegacyModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.ParticleSystemModule">
      <HintPath>..\..\Assemblies\UnityEngine.ParticleSystemModule.dll</HintPath>
    </Reference>
    <Reference Include="Unity.TextMeshPro">
      <HintPath>..\..\Assemblies\Unity.TextMeshPro.dll</HintPath>
    </Reference>
    <Reference Include="csharpsynth">
      <HintPath>..\..\Assemblies\csharpsynth.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UnityWebRequestModule">
      <HintPath>..\..\Assemblies\UnityEngine.UnityWebRequestModule.dll</HintPath>
    </Reference>
    <Reference Include="Sanford.Multimedia.Midi">
      <HintPath>..\..\Assemblies\Sanford.Multimedia.Midi.dll</HintPath>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>..\..\Assemblies\Newtonsoft.Json.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>