namespace Microsoft.CSharp.RuntimeBinder.Syntax
{
	internal enum TokenKind : byte
	{
		ArgList = 0,
		MakeRef = 1,
		RefType = 2,
		RefValue = 3,
		As = 4,
		Base = 5,
		Checked = 6,
		Explicit = 7,
		False = 8,
		Implicit = 9,
		Is = 10,
		Null = 11,
		This = 12,
		True = 13,
		TypeOf = 14,
		Unchecked = 15,
		Void = 16,
		Equal = 17,
		PlusEqual = 18,
		MinusEqual = 19,
		SplatEqual = 20,
		SlashEqual = 21,
		PercentEqual = 22,
		AndEqual = 23,
		HatEqual = 24,
		BarEqual = 25,
		LeftShiftEqual = 26,
		RightShiftEqual = 27,
		Question = 28,
		Colon = 29,
		ColonColon = 30,
		LogicalOr = 31,
		LogicalAnd = 32,
		Bar = 33,
		Hat = 34,
		Ampersand = 35,
		EqualEqual = 36,
		NotEqual = 37,
		LessThan = 38,
		LessThanEqual = 39,
		GreaterThan = 40,
		GreaterThanEqual = 41,
		LeftShift = 42,
		RightShift = 43,
		Plus = 44,
		Minus = 45,
		Splat = 46,
		Slash = 47,
		Percent = 48,
		Tilde = 49,
		Bang = 50,
		PlusPlus = 51,
		MinusMinus = 52,
		Dot = 53,
		QuestionQuestion = 54,
		Unknown = 55
	}
}
